### ISSUE TITLE
Strings of 26 bytes or more get packed as str8. Strings less than 32 bytes should be fixstr.

### ISSUE THREAD

**Issue by jkjuopperi** [hirotakan/MessagePacker#31]
https://github.com/hirotakan/MessagePacker/blob/2bd864d286e4761fe5c456dba568888cd9ced111/Sources/MessagePackTypes/MessagePackType%2BStringType.swift#L22

A string of e.g. 26 bytes will be packed in fixstr, though the spec says fixstr stores a byte array whose length is up to 31 bytes. Seem that the limit is wrong.

https://github.com/msgpack/msgpack/blob/master/spec.md#str-format-family

In our use case, our iOS and Android apps end up serializing the data differently and signatures don't match. We are using the Java Msgpack library on Android.

**Comment by hirotakan** [comment]
@jkjuopperi 
I fixed it with this [PR](https://github.com/hirotakan/MessagePacker/pull/32) and released [v0.4.2](https://github.com/hirotakan/MessagePacker/releases/tag/0.4.2).
Please try a new version.

Thank you!!
