### ISSUE TITLE
MessagePackExtension default initialization unavailable

### ISSUE THREAD

**Issue by snej** [hirotakan/MessagePacker#50]
## Problem

It’s not possible for a client of the framework to initialize a `MessagePackExtension` with a `type` and `data`; it results in a compile error. There is a workaround, though.

## Example

The following code, compiled outside the MessagePacker package:

```swift
import MessagePacker

var ext = MessagePackExtension(type: Int8(1), data: Data())
```

will fail to compile with these errors:

```
/Users/snej/Projects/BLIP-Swift/BLIP-Swift/Capability.swift:50:19: error: no exact matches in call to initializer 
        var ext = MessagePackExtension(type: Int8(1), data: Data())
                  ^
/Users/snej/Library/Developer/Xcode/DerivedData/BLIP-Swift-ertqqmqyjxcexgamkgpqvrypkloh/SourcePackages/checkouts/MessagePacker/Sources/MessagePackExtension.swift:17:12: note: candidate expects value of type 'MessagePackTimestamp' for parameter #1 (got '(type: Int8, data: @lvalue Data)')
    public init(timestamp: MessagePackTimestamp) {
           ^
/Users/snej/Library/Developer/Xcode/DerivedData/BLIP-Swift-ertqqmqyjxcexgamkgpqvrypkloh/SourcePackages/checkouts/MessagePacker/Sources/MessagePackExtension.swift:36:12: note: candidate expects value of type 'any Decoder' for parameter #1 (got '(type: Int8, data: @lvalue Data)')
    public init(from decoder: Decoder) throws {
           ^
```

The compiler sees the two explicit initializers in extensions, and insists on using one of those.

The problem, I think, is that MessagePacker doesn’t have any explicit `(Int8, Data)` initializer function. Inside the framework you can use the implicit initializer (e.g. at the bottom of MessagePackType+ExtensionType.swift), but for some reason outside the framework you can’t.

## Fix

Explicitly implementing the `(Int8, Data)` initializer should fix this.

## Workaround

```swift
var ext = MessagePackExtension(timestamp: MessagePackTimestamp(date: Date.now))
ext.data = myData
ext.type = myType
```

**Comment by hirotakan** [comment]
Released in 0.4.7.
Thank you @snej !
